version: '3.10-slim'

services:
  mi-app-interfaz-tkinter:
    image: sha256:cbf76e57a4afb8cc31c923652e14a277180bc969b75d1e98a8c79405cb255aff
    environment:
      - DISPLAY=$DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    command: python3 /app/tarea/interfaz.py
